USE pdv;

INSERT IGNORE INTO controle_versao_bd VALUES (1, 'V_RLS_10_46_2_3');
INSERT IGNORE INTO situacao_ecf values (0,0,0,0,0,0,0);
INSERT IGNORE INTO executar_funcao_keycode VALUES (1,  72, 'PRE VENDA');
INSERT IGNORE INTO executar_funcao_keycode VALUES (1,  73, 'CARTAO PRESENTE');
INSERT IGNORE INTO executar_funcao_keycode VALUES (1,  76, 'ALTERAR PRECO PRODUTO');
INSERT IGNORE INTO executar_funcao_keycode VALUES (1, 115, 'CANCELAR ITEM');
INSERT IGNORE INTO executar_funcao_keycode VALUES (1, 116, 'CANCELAR CUPOM');
INSERT IGNORE INTO executar_funcao_keycode VALUES (1,  85, 'CANCELAR CUPOM ANTERIOR');
INSERT IGNORE INTO executar_funcao_keycode VALUES (1, 120, 'CORBAN/RECARGA CELULAR');
INSERT IGNORE INTO executar_funcao_keycode VALUES (1, 112, 'INFORMAR FIDELIDADE');
INSERT IGNORE INTO executar_funcao_keycode VALUES (1,  86, 'SUSPENDER/RECUPERAR VENDA');
INSERT IGNORE INTO executar_funcao_keycode VALUES (1, 700, 'CHAMA FILA');
INSERT IGNORE INTO cadastro_skin VALUES (1, 'econect', 1, 1, 0);
INSERT IGNORE INTO estado VALUES ('AC', 'Acre');
INSERT IGNORE INTO estado VALUES ('AL', 'Alagoas');
INSERT IGNORE INTO estado VALUES ('AM', 'Amazonas');
INSERT IGNORE INTO estado VALUES ('AP', 'Amapa');
INSERT IGNORE INTO estado VALUES ('BA', 'Bahia');
INSERT IGNORE INTO estado VALUES ('CE', 'Ceara');
INSERT IGNORE INTO estado VALUES ('DF', 'Distrito Federal');
INSERT IGNORE INTO estado VALUES ('ES', 'Espirito Santo');
INSERT IGNORE INTO estado VALUES ('GO', 'Goias');
INSERT IGNORE INTO estado VALUES ('MA', 'Maranhao');
INSERT IGNORE INTO estado VALUES ('MG', 'Minas Gerais');
INSERT IGNORE INTO estado VALUES ('MS', 'Mato Grosso do Sul');
INSERT IGNORE INTO estado VALUES ('MT', 'Mato Grosso');
INSERT IGNORE INTO estado VALUES ('PA', 'Para');
INSERT IGNORE INTO estado VALUES ('PB', 'Paraiba');
INSERT IGNORE INTO estado VALUES ('PE', 'Pernambuco');
INSERT IGNORE INTO estado VALUES ('PI', 'Piaui');
INSERT IGNORE INTO estado VALUES ('PR', 'Parana');
INSERT IGNORE INTO estado VALUES ('RJ', 'Rio de Janeiro');
INSERT IGNORE INTO estado VALUES ('RN', 'Rio Grande do Norte');
INSERT IGNORE INTO estado VALUES ('RO', 'Rondonia');
INSERT IGNORE INTO estado VALUES ('RR', 'Roraima');
INSERT IGNORE INTO estado VALUES ('RS', 'Rio Grande do Sul');
INSERT IGNORE INTO estado VALUES ('SC', 'Santa Catarina');
INSERT IGNORE INTO estado VALUES ('SE', 'Sergipe');
INSERT IGNORE INTO estado VALUES ('SP', 'Sao Paulo');
INSERT IGNORE INTO estado VALUES ('TO', 'Tocantins');
