# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:
  
jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: azure/docker-login@v1
        with:
           login-server: ghcr.io
           username: ${{ secrets.GH_PACKAGES_USER }}
           password: ${{ secrets.GH_PACKAGES_TOKEN }}            
           
      - run: |
            docker build -t ghcr.io/socin-econect/environment-concentrador:latesr -f Dockerfile .
            docker tag ghcr.io/socin-econect/environment-concentrador:lastest ghcr.io/socin-econect/environment-concentrador:${{ github.sha }}
            
      - run: |
            docker push ghcr.io/socin-econect/environment-concentrador:latest
            docker push ghcr.io/socin-econect/environment-concentrador:${{ github.sha }}
          
