# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:
  
jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: azure/docker-login@v1
        with:
           login-server: ghcr.io
           username: ${{ secrets.GH_PACKAGES_USER }}
           password: ${{ secrets.GH_PACKAGES_TOKEN }}            
           
      - run: |
            docker build -t ghcr.io/fghenrique/exemplo-docker/teste-docker:latesr -f Dockerfile .
            docker tag ghcr.io/fghenrique/exemplo-docker/teste-docker:lastest ghcr.io/fghenrique/exemplo-docker/teste-docker:${{ github.sha }}
            
      - run: |
            docker push ghcr.io/fghenrique/exemplo-docker/teste-docker:latest
            docker push ghcr.io/fghenrique/exemplo-docker/teste-docker:${{ github.sha }}
          
